language: rust
cache:
  cargo: true

git:
  depth: 1

if: tag IS blank
script: make $SUITE

matrix:
  include:
    - os: linux
      env: SUITE=test
    - os: linux
      env: SUITE=test
      rust: "1.21.0"
    - os: linux
      env: SUITE=format-check
      install: rustup component add rustfmt-preview

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/37b5324c-46d2-11e8-9c92-0a580a28001f/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
