os: linux
language: rust
cache:
  cargo: true

git:
  depth: 1

branches:
  only:
    - master

script: make $SUITE

matrix:
  include:
    - env: SUITE=test
    - env: SUITE=test
      rust: "1.28.0"
    - env: SUITE=format-check
      install: rustup component add rustfmt-preview
    - env: SUITE=lint
      install: rustup component add clippy-preview
      rust: nightly

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/37b5324c-46d2-11e8-9c92-0a580a28001f/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
