os: linux
language: rust
cache:
  cargo: true

git:
  depth: 1

branches:
  only:
    - master
    - /^release\/.+$/

script: make $SUITE

matrix:
  include:
    - env: SUITE=test
    - env: SUITE=style
    - env: SUITE=lint

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/37b5324c-46d2-11e8-9c92-0a580a28001f/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
