[package]
name = "sentry-types"
version = "0.14.1"
license = "Apache-2.0"
description = "Common reusable types for implementing the sentry.io protocol."
homepage = "https://sentry.io/"
repository = "https://github.com/getsentry/rust-sentry-types"
documentation = "https://docs.rs/sentry-types"
keywords = ["sentry", "protocol"]
readme = "README.md"
authors = ["Sentry <hello@sentry.io>"]
exclude = [
    ".vscode/**/*",
    "scripts/**/*"
]
edition = "2018"

[features]
default = ["with_protocol"]
with_protocol = []

[badges]
travis-ci = { repository = "getsentry/rust-sentry-types" }

[dependencies]
thiserror = "1.0.15"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.46"
url = { version = "2.1.1", features = ["serde"] }
chrono = { version = "0.4.10", features = ["serde"] }
uuid = { version = "0.8.1", features = ["v4", "serde"] }
debugid = { version = "0.7.2", features = ["serde"] }
